freshshop/freshshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/',include('users.urls',namespace="users")),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^',include('goods.urls',namespace='goods')),
    url(r'^cart/',include('shoppingCart.urls',namespace='shopping')),
    url(r'^order/',include('order.urls',namespace='order')),
    #url(r'^search/', include('haystack.urls')),
]

freshshop/goods/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^goods/(\d+)$',views.detail,name='detail'),
    url(r'^goods/(\d+)/(\d+)/(\d+)$',views.good_list,name='list'),
    url(r'^search/',views.MySearch()),
]

freshshop/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$', views.register,name='register'),
    url(r'^register_handler/$', views.register_handler),
    url(r'^register_exist/$',views.register_exist),
    url(r'^login/$', views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^center_info/$', views.center_info,name="center_info"),
    url(r'^center_site/$', views.center_site,name="center_site"),
    url(r'^pro_id/(\d*)$', views.pro_id),
    url(r'^address_handler/(\d*)$', views.address_handler, name='address_handler'),
    url(r'^editor/(\d*)$',views.editor),
    url(r'^del_address/(\d*)$',views.del_address),
    url(r'^center_order/(\d+)$',views.center_order,name="center_order"),
]

freshshop/order/models.py
# coding=utf-8
from django.db import models

# Create your models here.
# 创建订单类模型，用于获取订单信息并维护
class Orderinfo(models.Model):
    oid = models.CharField(max_length=18,primary_key=True,verbose_name="订单编号")
    ouser = models.ForeignKey('users.Userinfo',verbose_name="用户")
    oaddress = models.CharField(max_length=130,verbose_name="收货地址")
    odate = models.DateTimeField(auto_now=True,verbose_name="下单日期")
    ototal = models.DecimalField(max_digits=6,decimal_places=2,verbose_name="订单总额")
    opay = models.ForeignKey('Payway',verbose_name="支付方式")
    ostate = models.ForeignKey('Order_state',verbose_name="订单状态") # 订单状态，1为未支付，2为已支付，未发货，3为已支付并发货，4为取消订单

# 创建订单详情，与订单类关联
class Orderdetail(models.Model):
    dorder = models.ForeignKey('Orderinfo',verbose_name="订单编号")
    ogoods = models.ForeignKey('goods.Goodsinfo',verbose_name="订单商品")
    oprice = models.DecimalField(max_digits=5,decimal_places=2,verbose_name="订单单价")
    ocount = models.IntegerField(verbose_name="订单数量")


# 创建支付方式模型，用于获取用户所选支付方式
class Payway(models.Model):
    pname = models.CharField(max_length=10,verbose_name="支付方式")
    pway = models.IntegerField(verbose_name="数字码") # 1：货到付款 2：微信支付 3：支付宝支付 4：银行卡支付

    def __unicode__(self):
        return self.pname

class Order_state(models.Model):
    state = models.IntegerField(primary_key=True,verbose_name='订单状态码')
    sname = models.CharField(max_length=10,verbose_name='订单状态')

    def __unicode__(self):
        return self.sname

freshshop/users/models.py
# coding:utf-8
from django.db import models

# Create your models here.


class Userinfo(models.Model):
    uname = models.CharField(max_length=20,verbose_name="用户名")
    upwd = models.CharField(max_length=40,verbose_name="密码")
    uemail = models.CharField(max_length=40,verbose_name="邮箱", default='')
    uphone = models.CharField(max_length=11,verbose_name="手机号码", default='')

    class Meta:
        db_table = 'Userinfo'

    def __unicode__(self):
        return self.uname


class Addressinfo(models.Model):
    pro = models.CharField(max_length=20, verbose_name="省", default='')
    city = models.CharField(max_length=20, verbose_name="市", default='')
    dis = models.CharField(max_length=20, verbose_name="区", default='')
    detail = models.CharField(max_length=30, verbose_name="详细地址", default='')
    recipients = models.CharField(max_length=20,verbose_name="收件人", default='')
    apostcode = models.CharField(max_length=6,verbose_name="邮政编码", default='')
    aphone = models.CharField(max_length=11, verbose_name="手机号码", default='')
    auser = models.ForeignKey('Userinfo')

    class Meta:
        db_table = 'UserAddress'

class Areasinfo(models.Model):
    atitle = models.CharField(max_length=20, verbose_name="省/市/区")
    pid = models.ForeignKey('self', null=True, blank=True)

freshshop/users/views.py
# coding=utf-8
from django.shortcuts import render,redirect
from .models import *
from goods.models import Goodsinfo
from hashlib import sha1
from login_validate import user_login
from django.db import transaction
from task import register_email
from django.core.urlresolvers import reverse
from order.models import *
from django.core.paginator import Paginator
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from django.views.decorators.http import require_http_methods,require_GET,require_POST
# Create your views here.


@require_GET
def register(request):
    return render(request,'users/register.html',{'title':'注册'})


@require_POST
def register_handler(request):
    post = request.POST
    user = Userinfo()
    name = post.get('user_name')
    phone = post.get('phone')
    user.uname = name
    pwd1 = post.get('pwd')
    pwd2 = post.get('cpwd')
    if pwd1 != pwd2:
        return render(request,'users/register.html')
    m = sha1()
    m.update(pwd1)
    pwd = m.hexdigest()
    user.upwd = pwd
    email = post.get('email')
    user.uemail = email
    user.uphone = phone
    user.save()
    register_email.delay(name,email)
    return render(request,'users/login.html')


def register_exist(request):
    name = request.GET.get('name')
    phone = request.GET.get('phone')
    user_num = Userinfo.objects.filter(uname=name).count()
    user_phone = Userinfo.objects.filter(uphone=phone).count()
    list3 = [{'user_num':user_num,'user_phone':user_phone}]
    return JsonResponse({'count':list3})


@require_http_methods(['GET','POST'])
def login(request):
    if request.method == 'GET':
        name = request.COOKIES.get('user_name','')
        content = {'title': '登录', 'error_name': 0, 'error_pwd': 0, 'uname': name, 'upwd': ''}
        return render(request,'users/login.html',content)
    post = request.POST
    name = post.get('username')
    pwd = post.get('pwd')
    user = Userinfo.objects.filter(uname=name)
    if len(user) == 0:
        content = {'title':'登录','error_name':1,'error_pwd':0,'uname':name,'upwd':pwd}
        return render(request, 'users/login.html',content)
    else:
        m = sha1()
        m.update(pwd)
        if m.hexdigest() == user[0].upwd:
            url = request.COOKIES.get('url','/')
            red = HttpResponseRedirect(url)
            if post.get('abc') == "1":
                red.set_cookie('user_name',name)
            else:
                red.set_cookie('user_name', '',max_age=-1)
            request.session['user_id'] = user[0].id
            request.session['user_name'] = name
            request.session['uphone'] = user[0].uphone
            request.session.set_expiry(0)
            return red
        else:
            content = {'title': '登录', 'error_name': 0, 'error_pwd': 1, 'uname': name, 'upwd': pwd}
            return render(request, 'users/login.html', content)


@require_GET
def logout(request):
    request.session.flush()
    return HttpResponseRedirect('/')

@require_GET
@user_login
def center_info(request):
    id1 = request.session.get('user_id','')
    user = Userinfo.objects.get(id=id1)
    phone = request.session.get('uphone','')
    goods_ids = request.COOKIES.get('goods_ids','')
    if goods_ids != '':
        goods_ids_list = goods_ids.split(',')
        goods_list = []
        for goods_id in goods_ids_list:
            goods_list.append(Goodsinfo.objects.get(id=int(goods_id)))
    else:
        goods_list = ""
    content = {'page_num':1,'title':'用户中心','uname':request.session.get('user_name',''),'email':user.uemail,
               'phone_error':0,'phone':phone,'goods_list':goods_list}
    return render(request, 'users/user_center_info.html', content)


@require_http_methods(['GET','POST'])
@user_login
def center_site(request):
    sid = request.session.get('user_id','')
    user = Userinfo.objects.get(id=sid)
    address = user.addressinfo_set.all()
    return render(request,'users/user_center_site.html',{'page_num':1,'title':'用户中心','address': address})


@require_http_methods(['GET','POST'])
def pro_id(request, p1):
    if p1 == '':
        areas_list = Areasinfo.objects.filter(pid__isnull=True)
    else:
        p2 = int(p1)
        areas_list = Areasinfo.objects.filter(pid_id=p2)
    list1 = []
    for li in areas_list:
        list1.append({'aid': li.id, 'city': li.atitle})
    return JsonResponse({'list1': list1})


@require_POST
def address_handler(request,p1):
    post = request.POST
    pid, cid, did = post.get('pro'), post.get('city'), post.get('dis')
    t1 = Areasinfo.objects.get(id=pid)
    t2 = Areasinfo.objects.get(id=cid)
    t3 = Areasinfo.objects.get(id=did)
    det = post.get('address')
    if p1 != '':
        p2 = int(p1)
        address = Addressinfo.objects.get(id = p2)
    else:
        address = Addressinfo()
    with transaction.atomic():
        address.recipients, address.aphone, address.apostcode = post['shoujian'], post['phone'], post['postcode']
        if t1.atitle == t2.atitle:
            t2.atitle = ''
        address.pro, address.city, address.dis, address.detail = t1.atitle, t2.atitle, t3.atitle, det
        address.auser_id = request.session['user_id']
        address.save()
    return redirect(reverse('users:center_site'))


@require_POST
def editor(request,p1):
    p1 = int(p1)
    address = Addressinfo.objects.get(id=p1)
    pro = address.pro
    city = address.city
    dis = address.dis
    areas = Areasinfo.objects
    pro_id = areas.get(atitle=pro).id
    city_id = areas.get(atitle=city).id
    dis_id = areas.get(atitle=dis).id
    det = address.detail
    shoujian = address.recipients
    pc = address.apostcode
    phone = address.aphone
    content = [{'pro_id':pro_id,'city_id':city_id,'dis_id':dis_id,'det':det, 'shoujian':shoujian,'pc':pc,'phone':phone}]
    return JsonResponse({'list1':content})


@require_GET
def del_address(request,p1):
    p2 = int(p1)
    Addressinfo.objects.get(id=p2).delete()
    return redirect(reverse('users:center_site'))


@require_GET
@user_login
def center_order(request,p1):
    orders = Orderinfo.objects.all()
    paginator = Paginator(orders,3)
    page_list =paginator.page_range
    page = paginator.page(int(p1))
    order_goods_list = []
    for order in orders:
        order_goods_list.append(order.orderdetail_set.all())
    content = {'page_num':1,'title':'用户中心','orders':page,'page_list':page_list}
    return render(request,'users/user_center_order.html',content)

freshshop/templates/users/login.html
{% extends 'base_buttom.html' %}
{% block head %}
    <script type="text/javascript">
    $(function () {
        if ({{ error_name }}==1)
        {
            $('.name_input').next().show()
        }
        if ({{ error_pwd }}==1)
        {
            $('.pass_input').next().show()
        }
         $('.name_input').focus(function () {
             $('.name_input').next().hide()
             $('.pass_input').next().hide()
         })
        $('.pass_input').focus(function () {
            $('.pass_input').next().hide()
        })
    })
    </script>
{% endblock head%}
{% block body %}
	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'users:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action="/users/login/">
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ uname }}">
						<div class="user_error">用户名错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码" value="{{ upwd }}">
						<div class="pwd_error">用户名或者密码错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="abc", value="1" checked>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

freshshop/templates/users/register.html
{% extends 'base_buttom.html' %}
{% load static from staticfiles %}
{% block head %}
    <script type="text/javascript" src="{% static 'js/register.js'%}"></script>
{% endblock head%}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo" href="/"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'users:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="/users/register_handler/">
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
                    <li>
						<label>手机号码:</label>
						<input type="text" name="phone" id="phone">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
                    {% csrf_token %}
				</form>
			</div>

		</div>

	</div>
{% endblock %}

freshshop/templates/users/user_center_info.html
{% extends 'base.html' %}
{% block head %}
    <script>
    $(function () {
        if ({{ phone_error }}==0)
        {
            $('.uphone').show()
        }
    })
    </script>
{% endblock head %}
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:center_info'%}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'users:center_order' '1'%}">· 全部订单</a></li>
				<li><a href="{% url 'users:center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ uname }}</li>
							<li><span>联系邮箱：</span>{{ email }}</li>
							<li class="uphone" style="display: none"><span>联系电话：</span>{{ phone }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix" id="recent">
                    {% if goods_list != ""%}
                    {% for goods in goods_list %}
				<li>
					<a href="/goods/{{ goods.id }}"><img src="/static/media/{{ goods.gpic }}"></a>
					<h4><a href="/goods/{{ goods.id }}">{{ goods.gtitle }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goods.gprice }}</span>
						<span class="unit">{{ goods.gunit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                    {% endfor %}
                    {% endif %}
			</ul>
		</div>
		</div>
	</div>
{% endblock body %}

freshshop/templates/users/user_center_order.html
{% extends 'base.html' %}
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:center_info' %}">· 个人信息</a></li>
				<li><a href="user_center_order.html" class="active">· 全部订单</a></li>
				<li><a href="{% url 'users:center_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>

                {% for order in orders %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.odate }}</li>
					<li class="col02">订单号：{{ order.oid }}</li>
{#					<li class="col02 stress">{{ order.ostate.sname }}</li>		#}
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for goods in order.orderdetail_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><a href="/goods/{{ goods.ogoods.id }}"><img src="/static/media/{{ goods.ogoods.gpic }}"></a></li>
									<li class="col02">{{ goods.ogoods.gtitle|slice:'10' }}<em>{{ goods.oprice }}元/{{ goods.ogoods.gunit }}</em></li>
									<li class="col03">{{ goods.ocount }}</li>
									<li class="col04">{{ goods.oprice }}元</li>
								</ul>
                                {% endfor %}
							</td>

							<td width="15%">{{ order.ototal }}元</td>
							<td width="15%">{{ order.ostate.sname }}</td>
							<td width="15%"><a href="#" class="oper_btn">
                                {% if order.ostate_id == 1 %}
                                去付款
                                {% elif order.ostate_id == 2 %}
                                催促卖家
                                {% elif order.ostate_id == 3 %}
                                查看物流
                                {% else %}
                                再次购买
                                {% endif %}
                            </a></td>
						</tr>
					</tbody>
				</table>
                {% endfor %}

				<div class="pagenation">
                    {% if orders.has_previous %}
					    <a href="/users/center_order/{{ orders.previous_page_number }}">上一页</a>
                    {% endif %}
                    {% for pn in page_list %}
                        {% if pn == orders.number %}
                            <a href="javascript:;">{{ pn }}</a>
                        {% else %}
					        <a href="/users/center_order/{{ pn }}">{{ pn }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if orders.has_next %}
                        <a href="/users/center_order/{{ orders.next_page_number }}">下一页</a>
                    {% endif %}
				</div>
		</div>
	</div>
{% endblock body %}

freshshop/templates/users/user_center_site.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block head %}
    <script src="{% static 'js/province.js' %}" ></script>
{% endblock %}
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:center_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'users:center_order' '1'%}">· 全部订单</a></li>
				<li><a href="{% url 'users:center_site'%}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>收货地址：</dt>
                        {% for addr in address %}
						    <dd>{{ addr.pro }} {{ addr.city }} {{ addr.dis }} {{ addr.detail }}({{ addr.recipients }} 收)
                                {{ addr.aphone }} <a href="javascript:;" class="edits fl">编辑</a><span hidden>{{ addr.id }}</span><a href="/users/del_address/{{ addr.id }}" class="del_addr fr">删除</a></dd>
                        {% endfor %}
					</dl>					
				</div>
				<h3 class="common_title2" id="edit">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="{% url 'users:address_handler' ''%}" id="form1">
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="shoujian" id="user">
						</div>
                        <div class="form_group">
							<label>寄送地址：</label>
							<select name="pro" id="pro">
							    <option value="0">---请选择省---</option>
							</select>
							<select name="city" id="city">
							    <option value="0">---请选择市---</option>
							</select>
							<select name="dis" id="dis">
							    <option value="0">---请选择区---</option>
							</select>
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea name="address" class="site_area"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="postcode" id="pc">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="" name="phone" id="phone">
                            <span class="error_tip" style="display: none;color:red">手机号码为11位数字组合</span>
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
                        <span class="error_tip" style="display: none;color:red" id="empty">提示信息</span>
					</form>
				</div>
		</div>
	</div>
{% endblock body %}